"use client";

import * as React from "react";
import Link from "next/link";
import { Download, History } from "lucide-react";

import { Card } from "@/app/components/ui/Card";

import { HubBackButton } from "../HubBackButton";
import { type GeneratedReport, OPS_REPORTS_STORAGE_KEY } from "../_lib/ops-reports";

function downloadReportFile(r: GeneratedReport) {
  const rows = [
    ["ReportType", "Start", "End", "Format"],
    [r.draft.reportType, r.draft.startDate, r.draft.endDate, r.draft.format],
    [],
    ["Body"],
    [r.preview.replace(/\n/g, " | ")],
  ];
  const csv = "\uFEFF" + rows.map((row) => row.map((c) => `"${String(c).replace(/"/g, '""')}"`).join(",")).join("\n");
  const blob = new Blob([r.draft.format === "PDF" ? r.preview : csv], {
    type: r.draft.format === "PDF" ? "application/pdf" : "text/csv;charset=utf-8",
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  const safe = r.title.replace(/\s+/g, "-").slice(0, 48);
  a.download =
    r.draft.format === "PDF" ? `${safe}.pdf` : `${safe}.xlsx`;
  a.click();
  URL.revokeObjectURL(url);
}

const MOCK_ARCHIVES: GeneratedReport[] = [
  {
    id: "arch-1",
    title: "Security report (2026-02-01 – 2026-02-28)",
    createdAt: "2026-03-01T10:00:00.000Z",
    generatedBy: "cron@lms.com",
    sizeLabel: "312 KB",
    draft: {
      reportType: "Security",
      startDate: "2026-02-01",
      endDate: "2026-02-28",
      format: "PDF",
    },
    preview: "[Archived sample — Security — Feb 2026]",
  },
  {
    id: "arch-2",
    title: "Health report (2026-03-01 – 2026-03-15)",
    createdAt: "2026-03-16T08:30:00.000Z",
    generatedBy: "jordan.m@lms.com",
    sizeLabel: "156 KB",
    draft: {
      reportType: "Health",
      startDate: "2026-03-01",
      endDate: "2026-03-15",
      format: "XLSX",
    },
    preview: "[Archived sample — Health — Mar 2026]",
  },
];

function mergeReports(session: GeneratedReport[]): GeneratedReport[] {
  const byId = new Map<string, GeneratedReport>();
  for (const r of MOCK_ARCHIVES) byId.set(r.id, r);
  for (const r of session) byId.set(r.id, r);
  return Array.from(byId.values()).sort(
    (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
  );
}

export default function ReportHistoryPage() {
  const [reports, setReports] = React.useState<GeneratedReport[]>([]);

  React.useEffect(() => {
    try {
      const raw = sessionStorage.getItem(OPS_REPORTS_STORAGE_KEY);
      const list: GeneratedReport[] = raw ? (JSON.parse(raw) as GeneratedReport[]) : [];
      setReports(mergeReports(list));
    } catch {
      setReports(mergeReports([]));
    }
  }, []);

  return (
    <div className="space-y-6 bg-slate-50 text-slate-900">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <HubBackButton />
        <History className="h-6 w-6 text-indigo-400" aria-hidden />
      </div>

      <div>
        <h1 className="text-2xl font-semibold text-slate-900">Report history</h1>
        <p className="mt-1 text-sm text-slate-900/80">
          Session-generated runs merge with sample archives. Use{" "}
          <Link
            href="/operations/reports/report-generator"
            className="font-semibold text-indigo-400 underline-offset-2 hover:underline"
          >
            Report generator
          </Link>{" "}
          to add new files.
        </p>
      </div>

      <Card className="border-slate-200 bg-white shadow-sm">
        <div className="overflow-x-auto rounded-lg border border-slate-200">
          <table className="min-w-[880px] w-full border-collapse text-sm">
            <thead>
              <tr className="border-b border-slate-200 bg-slate-50 text-left text-xs uppercase tracking-wider text-slate-900">
                <th className="px-4 py-3">Report name</th>
                <th className="px-4 py-3">Date generated</th>
                <th className="px-4 py-3">Generated by</th>
                <th className="px-4 py-3">Size</th>
                <th className="px-4 py-3 text-right">Download</th>
              </tr>
            </thead>
            <tbody>
              {reports.map((r) => (
                <tr key={r.id} id={`report-${r.id}`} className="border-t border-slate-200">
                  <td className="px-4 py-3 font-medium text-slate-900">{r.title}</td>
                  <td className="whitespace-nowrap px-4 py-3 text-slate-900">
                    {new Date(r.createdAt).toLocaleString()}
                  </td>
                  <td className="px-4 py-3 font-mono text-xs text-slate-900">{r.generatedBy}</td>
                  <td className="whitespace-nowrap px-4 py-3 text-slate-900">{r.sizeLabel}</td>
                  <td className="px-4 py-3 text-right">
                    <button
                      type="button"
                      onClick={() => downloadReportFile(r)}
                      className="inline-flex items-center gap-1.5 rounded-lg bg-indigo-400 px-3 py-2 text-xs font-semibold text-white shadow-sm transition-colors hover:bg-indigo-500"
                    >
                      <Download className="h-3.5 w-3.5" aria-hidden />
                      Download
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
}
